# Generated by Django 5.0.7 on 2024-08-11 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythontutorial',
            name='content',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
