# Generated by Django 5.0.7 on 2024-08-11 08:53

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0002_pythontutorial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythontutorial',
            name='content_with_uploads',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythontutorial',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pythontutorial',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='No content yet', null=True),
        ),
    ]
