# Generated by Django 5.0.7 on 2024-08-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0004_remove_pythontutorial_content_with_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='python_tutorial.pythontutorial')),
            ],
        ),
    ]
