# Generated by Django 5.0.7 on 2024-08-11 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0005_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, default='No content yet', null=True),
        ),
    ]
