# Generated by Django 5.0.7 on 2024-08-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0007_topicsection_alter_pythontutorial_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='details',
        ),
        migrations.DeleteModel(
            name='PythonTutorial',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
