# Generated by Django 5.0.7 on 2024-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0002_topicsection_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
